"""
Alembic migration script template.

This is used when generating new migrations.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a65eac76b2b'
down_revision: Union[str, None] = '8ffc71e328d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration - create tables, add columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_run_bundles',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('bundle_sha256', sa.String(length=64), nullable=False),
    sa.Column('bundle_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'run_id', name='uq_research_run_bundles_run')
    )
    op.create_index(op.f('ix_research_run_bundles_bundle_sha256'), 'research_run_bundles', ['bundle_sha256'], unique=False)
    op.create_index(op.f('ix_research_run_bundles_run_id'), 'research_run_bundles', ['run_id'], unique=False)
    op.create_index('ix_research_run_bundles_sha256', 'research_run_bundles', ['tenant_id', 'bundle_sha256'], unique=False)
    op.create_index(op.f('ix_research_run_bundles_tenant_id'), 'research_run_bundles', ['tenant_id'], unique=False)
    op.drop_index('idx_candidate_current_company', table_name='candidate')
    op.drop_index('idx_candidate_current_title', table_name='candidate')
    op.drop_index('idx_candidate_home_country', table_name='candidate')
    op.drop_index('idx_candidate_location', table_name='candidate')
    op.drop_index('idx_candidate_promotability', table_name='candidate')
    op.drop_index('idx_candidate_search_vector', table_name='candidate', postgresql_using='gin')
    op.drop_index('idx_candidate_updated_at', table_name='candidate')
    op.drop_column('candidate', 'search_vector')
    op.drop_index('idx_candidate_assignment_candidate', table_name='candidate_assignment')
    op.drop_index('idx_candidate_assignment_role', table_name='candidate_assignment')
    op.create_index(op.f('ix_company_aliases_alias_name'), 'company_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_company_aliases_company_prospect_id'), 'company_aliases', ['company_prospect_id'], unique=False)
    op.drop_constraint('company_aliases_tenant_id_fkey', 'company_aliases', type_='foreignkey')
    op.alter_column('company_metrics', 'as_of_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_company_metrics_company_prospect_id'), 'company_metrics', ['company_prospect_id'], unique=False)
    op.create_index(op.f('ix_company_metrics_company_research_run_id'), 'company_metrics', ['company_research_run_id'], unique=False)
    op.create_index(op.f('ix_company_metrics_metric_key'), 'company_metrics', ['metric_key'], unique=False)
    op.drop_constraint('company_metrics_tenant_id_fkey', 'company_metrics', type_='foreignkey')
    op.alter_column('company_prospect_evidence', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               nullable=False)
    op.alter_column('company_prospect_evidence', 'source_url',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('company_prospect_evidence', 'evidence_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=3, scale=2),
               nullable=False)
    op.create_index('ix_company_prospect_evidence_prospect_id', 'company_prospect_evidence', ['company_prospect_id'], unique=False)
    op.create_index(op.f('ix_company_prospect_evidence_tenant_id'), 'company_prospect_evidence', ['tenant_id'], unique=False)
    op.drop_constraint('company_prospect_evidence_company_prospect_id_fkey', 'company_prospect_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'company_prospect_evidence', 'company_prospects', ['company_prospect_id'], ['id'])
    op.drop_column('company_prospect_evidence', 'evidence_snippet')
    op.drop_column('company_prospect_evidence', 'metadata')
    op.add_column('company_prospect_metrics', sa.Column('source_type', sa.String(length=100), nullable=False))
    op.add_column('company_prospect_metrics', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('company_prospect_metrics', sa.Column('data_confidence', sa.Numeric(precision=3, scale=2), nullable=False))
    op.alter_column('company_prospect_metrics', 'value_raw',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.alter_column('company_prospect_metrics', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=3),
               existing_nullable=True)
    op.alter_column('company_prospect_metrics', 'value_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
    op.drop_index('ix_company_prospect_metric_company_prospect_id', table_name='company_prospect_metrics')
    op.drop_index('ix_company_prospect_metric_metric_type', table_name='company_prospect_metrics')
    op.drop_index('ix_company_prospect_metric_type_year', table_name='company_prospect_metrics')
    op.create_index(op.f('ix_company_prospect_metrics_company_prospect_id'), 'company_prospect_metrics', ['company_prospect_id'], unique=False)
    op.create_index('ix_company_prospect_metrics_prospect_id', 'company_prospect_metrics', ['company_prospect_id'], unique=False)
    op.create_index(op.f('ix_company_prospect_metrics_tenant_id'), 'company_prospect_metrics', ['tenant_id'], unique=False)
    op.create_index('ix_company_prospect_metrics_type_year', 'company_prospect_metrics', ['metric_type', 'as_of_year'], unique=False)
    op.drop_constraint('company_prospect_metric_company_prospect_id_fkey', 'company_prospect_metrics', type_='foreignkey')
    op.create_foreign_key(None, 'company_prospect_metrics', 'company_prospects', ['company_prospect_id'], ['id'])
    op.drop_column('company_prospect_metrics', 'source')
    op.drop_column('company_prospect_metrics', 'metadata')
    op.alter_column('company_prospects', 'name_normalized',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    # First update null sector values before making it NOT NULL
    op.execute("UPDATE company_prospects SET sector = 'Unknown' WHERE sector IS NULL")
    op.alter_column('company_prospects', 'sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_company_prospect_company_research_run_id', table_name='company_prospects')
    op.drop_index('ix_company_prospect_is_pinned', table_name='company_prospects')
    op.drop_index('ix_company_prospect_manual_priority', table_name='company_prospects')
    op.drop_index('ix_company_prospect_name_normalized', table_name='company_prospects')
    op.drop_index('ix_company_prospect_relevance_score', table_name='company_prospects')
    op.drop_index('ix_company_prospect_status', table_name='company_prospects')
    op.drop_index('ix_company_prospects_normalized_company_id', table_name='company_prospects')
    op.create_index(op.f('ix_company_prospects_ai_rank'), 'company_prospects', ['ai_rank'], unique=False)
    op.create_index(op.f('ix_company_prospects_company_research_run_id'), 'company_prospects', ['company_research_run_id'], unique=False)
    op.create_index('ix_company_prospects_is_pinned', 'company_prospects', ['is_pinned'], unique=False)
    op.create_index('ix_company_prospects_manual_priority', 'company_prospects', ['manual_priority'], unique=False)
    op.create_index(op.f('ix_company_prospects_name_normalized'), 'company_prospects', ['name_normalized'], unique=False)
    op.create_index('ix_company_prospects_relevance_score', 'company_prospects', ['relevance_score'], unique=False)
    op.create_index('ix_company_prospects_run_id', 'company_prospects', ['company_research_run_id'], unique=False)
    op.create_index('ix_company_prospects_status', 'company_prospects', ['status'], unique=False)
    op.create_index(op.f('ix_company_prospects_tenant_id'), 'company_prospects', ['tenant_id'], unique=False)
    op.drop_constraint('company_prospect_converted_to_company_id_fkey', 'company_prospects', type_='foreignkey')
    op.drop_constraint('company_prospect_company_research_run_id_fkey', 'company_prospects', type_='foreignkey')
    op.drop_constraint('fk_company_prospects_role_mandate_id', 'company_prospects', type_='foreignkey')
    op.drop_constraint('fk_company_prospects_approved_by_user_id', 'company_prospects', type_='foreignkey')
    op.create_foreign_key(None, 'company_prospects', 'company_research_runs', ['company_research_run_id'], ['id'])
    op.create_foreign_key(None, 'company_prospects', 'role', ['role_mandate_id'], ['id'])
    op.create_foreign_key(None, 'company_prospects', 'company', ['normalized_company_id'], ['id'])
    op.create_foreign_key(None, 'company_prospects', 'user', ['approved_by_user_id'], ['id'])
    op.drop_column('company_prospects', 'linkedin_url')
    op.drop_column('company_prospects', 'converted_to_company_id')
    op.drop_index('ix_company_research_run_role_mandate_id', table_name='company_research_runs')
    op.drop_index('ix_company_research_run_status', table_name='company_research_runs')
    op.create_index('ix_company_research_runs_role_mandate_id', 'company_research_runs', ['role_mandate_id'], unique=False)
    op.create_index('ix_company_research_runs_status', 'company_research_runs', ['status'], unique=False)
    op.create_index(op.f('ix_company_research_runs_tenant_id'), 'company_research_runs', ['tenant_id'], unique=False)
    op.drop_constraint('company_research_run_created_by_user_id_fkey', 'company_research_runs', type_='foreignkey')
    op.drop_constraint('company_research_run_role_mandate_id_fkey', 'company_research_runs', type_='foreignkey')
    op.create_foreign_key(None, 'company_research_runs', 'role', ['role_mandate_id'], ['id'])
    op.create_foreign_key(None, 'company_research_runs', 'user', ['created_by_user_id'], ['id'])
    op.create_index(op.f('ix_research_events_company_research_run_id'), 'research_events', ['company_research_run_id'], unique=False)
    op.create_index(op.f('ix_research_events_event_type'), 'research_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_research_events_tenant_id'), 'research_events', ['tenant_id'], unique=False)
    op.alter_column('research_run_steps', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('research_run_steps', 'finished_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_research_run_steps_run_id'), 'research_run_steps', ['run_id'], unique=False)
    op.create_index(op.f('ix_research_run_steps_tenant_id'), 'research_run_steps', ['tenant_id'], unique=False)
    op.drop_index('uq_research_runs_tenant_idempotency', table_name='research_runs', postgresql_where='(idempotency_key IS NOT NULL)')
    op.create_index(op.f('ix_research_runs_company_research_run_id'), 'research_runs', ['company_research_run_id'], unique=False)
    op.create_index(op.f('ix_research_runs_tenant_id'), 'research_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_source_documents_company_research_run_id'), 'source_documents', ['company_research_run_id'], unique=False)
    op.create_index(op.f('ix_source_documents_content_hash'), 'source_documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_source_documents_tenant_id'), 'source_documents', ['tenant_id'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_tenant_id', table_name='user')
    op.drop_constraint('user_tenant_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration - drop tables, remove columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_tenant_id_fkey', 'user', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_user_tenant_id', 'user', ['tenant_id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_source_documents_tenant_id'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_content_hash'), table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_company_research_run_id'), table_name='source_documents')
    op.drop_index(op.f('ix_research_runs_tenant_id'), table_name='research_runs')
    op.drop_index(op.f('ix_research_runs_company_research_run_id'), table_name='research_runs')
    op.create_index('uq_research_runs_tenant_idempotency', 'research_runs', ['tenant_id', 'idempotency_key'], unique=True, postgresql_where='(idempotency_key IS NOT NULL)')
    op.drop_index(op.f('ix_research_run_steps_tenant_id'), table_name='research_run_steps')
    op.drop_index(op.f('ix_research_run_steps_run_id'), table_name='research_run_steps')
    op.alter_column('research_run_steps', 'finished_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('research_run_steps', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_research_events_tenant_id'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_event_type'), table_name='research_events')
    op.drop_index(op.f('ix_research_events_company_research_run_id'), table_name='research_events')
    op.drop_constraint(None, 'company_research_runs', type_='foreignkey')
    op.drop_constraint(None, 'company_research_runs', type_='foreignkey')
    op.create_foreign_key('company_research_run_role_mandate_id_fkey', 'company_research_runs', 'role', ['role_mandate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('company_research_run_created_by_user_id_fkey', 'company_research_runs', 'user', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_company_research_runs_tenant_id'), table_name='company_research_runs')
    op.drop_index('ix_company_research_runs_status', table_name='company_research_runs')
    op.drop_index('ix_company_research_runs_role_mandate_id', table_name='company_research_runs')
    op.create_index('ix_company_research_run_status', 'company_research_runs', ['status'], unique=False)
    op.create_index('ix_company_research_run_role_mandate_id', 'company_research_runs', ['role_mandate_id'], unique=False)
    op.add_column('company_prospects', sa.Column('converted_to_company_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('company_prospects', sa.Column('linkedin_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_prospects', type_='foreignkey')
    op.drop_constraint(None, 'company_prospects', type_='foreignkey')
    op.drop_constraint(None, 'company_prospects', type_='foreignkey')
    op.drop_constraint(None, 'company_prospects', type_='foreignkey')
    op.create_foreign_key('fk_company_prospects_approved_by_user_id', 'company_prospects', 'user', ['approved_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_company_prospects_role_mandate_id', 'company_prospects', 'role', ['role_mandate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('company_prospect_company_research_run_id_fkey', 'company_prospects', 'company_research_runs', ['company_research_run_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('company_prospect_converted_to_company_id_fkey', 'company_prospects', 'company', ['converted_to_company_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_company_prospects_tenant_id'), table_name='company_prospects')
    op.drop_index('ix_company_prospects_status', table_name='company_prospects')
    op.drop_index('ix_company_prospects_run_id', table_name='company_prospects')
    op.drop_index('ix_company_prospects_relevance_score', table_name='company_prospects')
    op.drop_index(op.f('ix_company_prospects_name_normalized'), table_name='company_prospects')
    op.drop_index('ix_company_prospects_manual_priority', table_name='company_prospects')
    op.drop_index('ix_company_prospects_is_pinned', table_name='company_prospects')
    op.drop_index(op.f('ix_company_prospects_company_research_run_id'), table_name='company_prospects')
    op.drop_index(op.f('ix_company_prospects_ai_rank'), table_name='company_prospects')
    op.create_index('ix_company_prospects_normalized_company_id', 'company_prospects', ['normalized_company_id'], unique=False)
    op.create_index('ix_company_prospect_status', 'company_prospects', ['status'], unique=False)
    op.create_index('ix_company_prospect_relevance_score', 'company_prospects', ['relevance_score'], unique=False)
    op.create_index('ix_company_prospect_name_normalized', 'company_prospects', ['name_normalized'], unique=False)
    op.create_index('ix_company_prospect_manual_priority', 'company_prospects', ['manual_priority'], unique=False)
    op.create_index('ix_company_prospect_is_pinned', 'company_prospects', ['is_pinned'], unique=False)
    op.create_index('ix_company_prospect_company_research_run_id', 'company_prospects', ['company_research_run_id'], unique=False)
    op.alter_column('company_prospects', 'sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('company_prospects', 'name_normalized',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('company_prospect_metrics', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('company_prospect_metrics', sa.Column('source', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_prospect_metrics', type_='foreignkey')
    op.create_foreign_key('company_prospect_metric_company_prospect_id_fkey', 'company_prospect_metrics', 'company_prospects', ['company_prospect_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_company_prospect_metrics_type_year', table_name='company_prospect_metrics')
    op.drop_index(op.f('ix_company_prospect_metrics_tenant_id'), table_name='company_prospect_metrics')
    op.drop_index('ix_company_prospect_metrics_prospect_id', table_name='company_prospect_metrics')
    op.drop_index(op.f('ix_company_prospect_metrics_company_prospect_id'), table_name='company_prospect_metrics')
    op.create_index('ix_company_prospect_metric_type_year', 'company_prospect_metrics', ['metric_type', 'as_of_year'], unique=False)
    op.create_index('ix_company_prospect_metric_metric_type', 'company_prospect_metrics', ['metric_type'], unique=False)
    op.create_index('ix_company_prospect_metric_company_prospect_id', 'company_prospect_metrics', ['company_prospect_id'], unique=False)
    op.alter_column('company_prospect_metrics', 'value_usd',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('company_prospect_metrics', 'currency',
               existing_type=sa.String(length=3),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('company_prospect_metrics', 'value_raw',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('company_prospect_metrics', 'data_confidence')
    op.drop_column('company_prospect_metrics', 'source_url')
    op.drop_column('company_prospect_metrics', 'source_type')
    op.add_column('company_prospect_evidence', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('company_prospect_evidence', sa.Column('evidence_snippet', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'company_prospect_evidence', type_='foreignkey')
    op.create_foreign_key('company_prospect_evidence_company_prospect_id_fkey', 'company_prospect_evidence', 'company_prospects', ['company_prospect_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_company_prospect_evidence_tenant_id'), table_name='company_prospect_evidence')
    op.drop_index('ix_company_prospect_evidence_prospect_id', table_name='company_prospect_evidence')
    op.alter_column('company_prospect_evidence', 'evidence_weight',
               existing_type=sa.Numeric(precision=3, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('company_prospect_evidence', 'source_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('company_prospect_evidence', 'source_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key('company_metrics_tenant_id_fkey', 'company_metrics', 'tenant', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_company_metrics_metric_key'), table_name='company_metrics')
    op.drop_index(op.f('ix_company_metrics_company_research_run_id'), table_name='company_metrics')
    op.drop_index(op.f('ix_company_metrics_company_prospect_id'), table_name='company_metrics')
    op.alter_column('company_metrics', 'as_of_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    op.create_foreign_key('company_aliases_tenant_id_fkey', 'company_aliases', 'tenant', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_company_aliases_company_prospect_id'), table_name='company_aliases')
    op.drop_index(op.f('ix_company_aliases_alias_name'), table_name='company_aliases')
    op.create_index('idx_candidate_assignment_role', 'candidate_assignment', ['tenant_id', 'role_id', 'status'], unique=False)
    op.create_index('idx_candidate_assignment_candidate', 'candidate_assignment', ['tenant_id', 'candidate_id'], unique=False)
    op.add_column('candidate', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed('((((((setweight(to_tsvector(\'english\'::regconfig, (COALESCE(first_name, \'\'::character varying))::text), \'A\'::"char") || setweight(to_tsvector(\'english\'::regconfig, (COALESCE(last_name, \'\'::character varying))::text), \'A\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, (COALESCE(current_title, \'\'::character varying))::text), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, (COALESCE(current_company, \'\'::character varying))::text), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(bio, \'\'::text)), \'C\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(tags, \'\'::text)), \'B\'::"char")) || setweight(to_tsvector(\'english\'::regconfig, COALESCE(cv_text, \'\'::text)), \'D\'::"char"))', persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_candidate_updated_at', 'candidate', ['tenant_id', 'updated_at'], unique=False)
    op.create_index('idx_candidate_search_vector', 'candidate', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_candidate_promotability', 'candidate', ['tenant_id', 'promotability_score'], unique=False)
    op.create_index('idx_candidate_location', 'candidate', ['tenant_id', 'location'], unique=False)
    op.create_index('idx_candidate_home_country', 'candidate', ['tenant_id', 'home_country'], unique=False)
    op.create_index('idx_candidate_current_title', 'candidate', ['tenant_id', 'current_title'], unique=False)
    op.create_index('idx_candidate_current_company', 'candidate', ['tenant_id', 'current_company'], unique=False)
    op.drop_index(op.f('ix_research_run_bundles_tenant_id'), table_name='research_run_bundles')
    op.drop_index('ix_research_run_bundles_sha256', table_name='research_run_bundles')
    op.drop_index(op.f('ix_research_run_bundles_run_id'), table_name='research_run_bundles')
    op.drop_index(op.f('ix_research_run_bundles_bundle_sha256'), table_name='research_run_bundles')
    op.drop_table('research_run_bundles')
    # ### end Alembic commands ###
