"""
Alembic migration script template.

This is used when generating new migrations.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd32464b5290'
down_revision: Union[str, None] = '7a65eac76b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration - create tables, add columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_jobs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=200), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_research_jobs_locked', 'research_jobs', ['locked_at', 'locked_by'], unique=False)
    op.create_index(op.f('ix_research_jobs_locked_at'), 'research_jobs', ['locked_at'], unique=False)
    op.create_index(op.f('ix_research_jobs_run_id'), 'research_jobs', ['run_id'], unique=False)
    op.create_index('ix_research_jobs_run_status', 'research_jobs', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_research_jobs_status'), 'research_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_research_jobs_tenant_id'), 'research_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_research_jobs_tenant_status', 'research_jobs', ['tenant_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse the migration - drop tables, remove columns, etc."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_research_jobs_tenant_status', table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_tenant_id'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_status'), table_name='research_jobs')
    op.drop_index('ix_research_jobs_run_status', table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_run_id'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_locked_at'), table_name='research_jobs')
    op.drop_index('ix_research_jobs_locked', table_name='research_jobs')
    op.drop_table('research_jobs')
    # ### end Alembic commands ###
